### ISSUE TITLE
Discussion about Abstract concepts about Lifelib 19/2/2019

### ISSUE THREAD

**Issue by NGKEVEN** [fumitoh/lifelib#5]
I have tried to read your tutorial about modelx and understood the basic concepts. The following are some recommendations about how to present the (actuarial) model in a more organized and nicer way. I dont know if they are good ideas or can be compatible with modelx though (I think you have mentioned similar ideas in your introduction to lifelib and your example in modelx, but you dont explicitly state them in much detail).

I find that for every time series variable (those with parameter t), its concept can be a combination of several other conceptual "classes". For example, 
ExpsCommInit's concept is actually a combination of 2 "classes"
1) Negative->Expenses->Commission
2) Event: Init
For the first class(actually a sequence of classes, which can be views as subsets of one another), this variable is a part of commission, which is a kind of expense, which may be considered as "negative"
For the second class, "Init" indicates that the variable should be charged at the beginning of the policy term. "Event" is a special class, which is comprised of 2 parts: 1) when will the event occurs 2) what is the probability of the event. "Event" include surrender/ death/ beginning of the policy term/ beginning of every survival period) etc. The default event should be the event of survival. Including concepts like "Event" is beneficial for changing between deterministic and stochastic scenarios.

Another example is ExpsCommTotal, it only contains 1 class
1) Negative->Expense->Commission ------------Total
"Total" should be a special name tag for the variable. Any other variable with class "Negative->Expense->Commission-> any other smaller classes" should be thought of "sons" of this variable. You can also say they "inherited" from this variable. (The concept of "inherit" here may be different from that in modelx documentation, about cells or spaces)

Many other variables may be different combination of many different classes (as opposed to your concept about a cell cannot be contained from 2 spaces). For example, some variables specific to certain accounting principles should have extra 1 "class" related to that accounting principle.

The nice thing about adding these concept of "classes" or "name tags" or whatever, is that it is good for "slicing of concepts". If I want to review all the variables about the event "surrender" I can choose the name tag (or class) "surrender", starting from the top (with total name tag), I can review several tree structures about it. It is even good for designing different products quickly. To change a critical illness to simple life, I can "uncheck" all the variables related to "hospital" and "illness". 

It may be possible to write a python script to produce the different python projects for different user-defined products. The python script has the ability to change all the variable unnecessary to commented segment(which has the same effect as deleting the variable, but clearer). The good thing about this is, the actuary will not be confused with many useless variables. The bad thing about this is, If we want to evaluate the aggregate level variable across different products, we have to run different scripts for different products.    

As I am not an experienced actuary, many of the above ideas may be useless or even bad. Feel free to comment though. Thanks.

**Comment by fumitoh** [comment]
I'm not fully understanding your ideas. You could try to further elaborate on them by prototyping but it's unlikely that the ideas will be incorporated into modelx as the fundamental design of modelx has been set. It may be possible to create models with modelx in a way that embodies your design ideas, but if not you may want to create your own tool. Thanks anyway for your deep thoughts.

**Comment by NGKEVEN** [comment]
Thanks for your reply! Let me explain more. 
For variable ExpsCommInit, which contains 2 "classes" or "attributes"
* Negative->Expenses->Commission
* Event: Init
I first create a set(which may be a dictionary or array or any other suitable collection like space ) called "Negative", then within this "Negative" I create "Expenses", then in which I create a set called "Commission". I put the pointer of this variable "ExpsCommInit" into this "Commission" set. I also put the pointer of "ExpsCommInit" to a set called "Event: Init". Also, I append the pointer of the set "Commission" and "Event: Init" to the variable "ExpsCommInit"(just like every html segment can have many attributes).  I continue to do this step for all other variables. So, finally every variable's pointer is included in 1 or more "set". If the user want to view any variables for any particular set (say commission), he should be able to do so, and focus on that particular group only. 

The idea of "Event" is simple. For example, instead of multiplying surrender benefit with surr rate, I multiply it with a variable "EventSurr". Then this EventSurr is a real random variable if the mode of the model is stochastic and it is equal to surr rate if the mode of the model is deterministic.

I will study the code of modelx within weeks, after I become more familiar with python. I will give more practical advises at that time. Thanks.
