### ISSUE TITLE
Reading "simplelife.mx" file

### ISSUE THREAD

**Issue by DemosthenisD** [fumitoh/lifelib#7]
Hi Fumito,

I copied the simplelife project. 
I see all the various *.py files that seem to be mainly the various UserSpaces.

 - How are these "triggering" a new UserSpace to be created (I cannot pin point the command in them for this)? I was expecting to see something like space="" or mx.new_space() or something like that...

 - How can we read the simplelife.mx file? Is this where the "coming together" of the various spaces takes place?

Thanks,
Demosthenis

**Comment by fumitoh** [comment]
`simplelife.py` is the trigger.  In it, there's a `build` function, which builds and returns a new `simplelife` model. 

You can restore `simplelife.mx` by [`modelx.restore_model`](https://docs.modelx.io/en/latest/reference/generated/modelx.restore_model.html#modelx.restore_model) function.

**Comment by DemosthenisD** [comment]
Thanks!
